CREATE TABLE services (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(100)   NOT NULL UNIQUE,
    duration_minutes INT            NOT NULL,
    price            NUMERIC(10, 2) NOT NULL
);

CREATE TABLE bookings (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id     BIGINT         NOT NULL REFERENCES services (id),
    booking_date   DATE           NOT NULL,
    start_time     TIME           NOT NULL,
    customer_name  VARCHAR(100)   NOT NULL,
    customer_email VARCHAR(255)   NOT NULL,
    total_price    NUMERIC(10, 2) NOT NULL,
    status         VARCHAR(20)    NOT NULL,
    -- TRUE while the booking is confirmed, NULL once cancelled. NULLs are distinct in a
    -- unique constraint, so only one confirmed booking can hold a slot while any number
    -- of cancelled ones may remain.
    active_slot    BOOLEAN,
    CONSTRAINT uq_bookings_active_slot UNIQUE (booking_date, start_time, active_slot)
);
